#Le.Zhang@TECH.BSP.Stability.PHOENIX_PROJECT 2022/4/21, Add for PHOENIX_PROJECT

obj-$(CONFIG_OPLUS_FEATURE_PHOENIX) += oplus_phoenix.o
oplus_phoenix-y := op_bootprof.o phoenix_dump.o phoenix_watchdog.o phoenix_base.o
